MangroveSpace/Controllers/NoticeController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MangroveSpace.Controllers
{
    [Authorize(Roles = "CmsNotice,SuperAdmin,admin")]
    public class NoticeController : Controller
    {
        private MangroveSpaceEntities db = new MangroveSpaceEntities();

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }

        // GET: Notice
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            try
            {
            List<dynamic> Information = Global.Sql(db, "select * from [dbo].[AspCMSNotice] where [NoticeCategory]='1' and [NoticeStatus]=1 order by [NoticeID] DESC").ToList();
            return View(Information);

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }


        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
            return View();

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }

        [Authorize]
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NoticeName,AttachFile,NoticeDescription,NoticeStatus,NoticeDate")] AspCMSNotice notice, HttpPostedFileBase AttFile)
        {
            try
            {
            string AttachFileName = "";
            string AttachFileExt = "";
            string AttachFolderPath = "";

            if (ModelState.IsValid)
            {

                int NoticeID = db.Database.SqlQuery<Int32>("select isnull(max([NoticeID])+1,1) from [AspCMSNotice]").Single();
                int NoticeOrderID = db.Database.SqlQuery<Int32>("select isnull(max([NoticeOrderID])+1,1) from [dbo].[AspCMSNotice] where [NoticeCategory]=1").Single();
                try
                {
                    string[] validateFile = new string[] { "text/plain", "application/pdf", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "image/jpeg", "image/jpg", "image/png", "image/gif", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" };
                    //bool bol = Array.Exists(validateFile, E => E == Validate);
                    string Validate = Global.GetMIMEType(AttFile.FileName);
                    if (validateFile.Contains(Validate))
                    {
                        AttachFileName = Path.GetFileNameWithoutExtension(AttFile.FileName);
                        AttachFileExt = Path.GetExtension(AttFile.FileName);
                        AttachFileName = "No-" + NoticeID + AttachFileExt;
                        AttachFolderPath = "/Uploads/NoticeFile/" + AttachFileName;

                        AttachFileName = Path.Combine(Server.MapPath("~/Uploads/NoticeFile/"), AttachFileName);
                        AttFile.SaveAs(AttachFileName);
                        notice.AttachFile = AttachFolderPath;

                    }
                    else
                    {
                        TempData["msgs"] = "Please select (pdf,doc,docx,xlx,png,jpeg,jpg,gif)";
                        return View(notice);
                    }

                }
                catch
                {
                    TempData["msgs"] = "Somthing Went Wrong";
                    AttachFolderPath = "";
                }

                notice.EntryDate = DateTime.Now;
                notice.NoticeOrderID = NoticeOrderID;
                notice.EntryBy = User.Identity.GetUserId();
                notice.NoticeID = NoticeID;
                notice.AttachFile = AttachFolderPath;
                notice.NoticeCategory = Convert.ToString(1);
                db.AspCMSNotices.Add(notice);
                db.SaveChanges();
                TempData["msg"] = "Successfuly Saved";
                return RedirectToAction("Index");

            }
            else
            {
                TempData["msgs"] = "Somthing Went Wrong";
                return View(notice);

            }

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }



        }


        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspCMSNotice Notice = db.AspCMSNotices.Find(id);
            if (Notice == null)
            {
                return HttpNotFound();
            }
            return View(Notice);

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }



        [Authorize]
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NoticeName,AttachFilePath,NoticeDescription,NoticeStatus,NoticeDate")] AspCMSNotice notice, HttpPostedFileBase AttachFilePath)
        {
            try
            {
            string AttachFileName = "";
            string AttachFileExt = "";
            string AttachFolderPath = "";

            if (ModelState.IsValid)
            {

                try
                {
                    string[] validateFile = new string[] { "text/plain", "application/pdf", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "image/jpeg", "image/jpg", "image/png", "image/gif", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" };
                    //bool bol = Array.Exists(validateFile, E => E == Validate);
                    string Validate = Global.GetMIMEType(AttachFilePath.FileName);
                    if (validateFile.Contains(Validate))
                    {
                        AttachFileName = Path.GetFileNameWithoutExtension(AttachFilePath.FileName);
                        AttachFileExt = Path.GetExtension(AttachFilePath.FileName);
                        AttachFileName = "No" + notice.NoticeID + AttachFileExt;
                        AttachFolderPath = "/Uploads/NoticeFile/" + AttachFileName;
                        notice.AttachFile = AttachFolderPath;
                        AttachFileName = Path.Combine(Server.MapPath("~/Uploads/NoticeFile/"), AttachFileName);
                        AttachFilePath.SaveAs(AttachFileName);
                        

                        notice.ModifyDate = DateTime.Now;
                        notice.ModifyBy = User.Identity.GetUserId();
                        db.Entry(notice).State = EntityState.Modified;
                        db.Entry(notice).Property(e => e.NoticeID).IsModified = false;

MangroveSpace/Views/Notice/AllNotice.cshtml
@model IEnumerable<dynamic>

@{

    Layout = Layout = "~/Views/Shared/frontend/" + this.Session["ThemeName"] + "/_InnerPageLayout.cshtml";
    ViewBag.Title = "All Notice";
}
@{
    Html.RenderPartial("~/Views/Shared/frontend/" + this.Session["ThemeName"] + "/_NoticeAllPartial.cshtml", Model);
}

MangroveSpace/Views/Notice/CodeViewEdit.cshtml
@model AspCMSNotice

@{
    /**/

    ViewBag.Title = "Code View Edit";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}



<div class="row">
    <div class="col-md-12">
        <div class="page-title">
            <div class="row">
                <div class="col-md-6">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="col-md-6 text-right">
                    <a href="@Url.Action("Index", "Notice")" class="btn btn-success">Manage Notice</a>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="row">


    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <br />
                @using (Html.BeginForm("Edit", "Notice", null, FormMethod.Post, new { @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.ID)
                    @Html.HiddenFor(m => m.NoticeID)


                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NoticeDescription, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="code-container">
                                        @Html.TextAreaFor(model => model.NoticeDescription)
                                        @Html.ValidationMessageFor(m => m.NoticeDescription)
                                    </div>
                                    <a class="btn btn-info pull-right btn-xs" style="margin-top:5px;margin-right:0" href="javascript:autoFormatSelection()">
                                        <i class="fa fa-check"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NoticeName, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    @Html.EditorFor(model => model.NoticeName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(m => m.NoticeName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.NoticeDate, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div id="filterDate2">

                                        <!-- Datepicker as text field -->
                                        <div class="input-group date cus_date_3" data-provide="datepicker" data-date-format="mm.dd.yyyy">
                                            @Html.EditorFor(model => model.NoticeDate, "{0:dd/MM/yyyy}", new { htmlAttributes = new { @class = "form-control StudentBirthDay", data_date_format = "mm.dd.yyyy", placeholder = "mm/dd/yy" } })
                                            @Html.ValidationMessageFor(m => m.NoticeDate)
                                            <div class="input-group-addon">
                                                <span class="glyphicon glyphicon-th"></span>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.NoticeStatus, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    @*@Html.EditorFor(model => model.AspInfoSection.SectionShift, new { htmlAttributes = new { @class = "form-control" } })*@
                                    @Html.DropDownListFor(model=>model.NoticeStatus, new SelectList(new List<SelectListItem>{
                                            new SelectListItem { Text="", Value=string.Empty},
                                            new SelectListItem { Text="Publish", Value="true"},
                                            new SelectListItem { Text="Unpublish", Value="false"},

                                        },"Value","Text"), new { @class = " js-example-basic-single form-control ", name = "AspCMSSlider.SliderStatus" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-12 col-sm-12 col-xs-12" style="margin-bottom:10px"></label>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="file_uploader">
                                        <span id="filename">Select your file</span>
                                        <label for="file-upload">Browse<input type="file" id="file-upload"></label>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                    <div class="ln_solid"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-12 text-center col-sm-12 col-xs-12 ">
                                    <a href="/Notice/" class="btn btn-primary" type="button">Cancel</a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")



    <script>
        var editor = CodeMirror.fromTextArea(document.getElementById("NoticeDescription"), {
            lineNumbers: true,
            mode: "htmlmixed"
        });
        CodeMirror.commands["selectAll"](editor);

        function getSelectedRange() {
            return { from: editor.getCursor(true), to: editor.getCursor(false) };
        }

        function autoFormatSelection() {
            var range = getSelectedRange();
            editor.autoFormatRange(range.from, range.to);
        }

        function commentSelection(isComment) {
            var range = getSelectedRange();
            editor.commentRange(isComment, range.from, range.to);
        }
    </script>





}

MangroveSpace/Views/Notice/Create.cshtml
@model AspCMSNotice
@{
    ViewBag.Title = "Add Notice";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="page-title">
            <div class="row">
                <div class="col-md-6">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="col-md-6 text-right">
                    <a href="@Url.Action("Index", "Notice")" class="btn btn-success">Manage Notice</a>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="row">


    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <br />
                @using (Html.BeginForm("Create", "Notice", null, FormMethod.Post, new { @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    if (TempData["msgs"] != null)
                    {
                        <div style="text-align:center;font-size:16px;color:red;">
                            <span>@TempData["msgs"]</span>
                        </div>

                    }
                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NoticeDescription, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    @Html.TextAreaFor(model => model.NoticeDescription)
                                    @Html.ValidationMessageFor(m => m.NoticeDescription)
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.NoticeName, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    @Html.EditorFor(model => model.NoticeName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(m => m.NoticeName)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.NoticeDate, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div id="filterDate2">

                                        <!-- Datepicker as text field -->
                                        <div class="input-group date cus_date_3" data-provide="datepicker" data-date-format="mm.dd.yyyy">
                                            @Html.EditorFor(model => model.NoticeDate, "{0:dd/MM/yyyy}", new { htmlAttributes = new { @class = "form-control StudentBirthDay", data_date_format = "mm.dd.yyyy", placeholder = "mm/dd/yy" } })
                                            
                                            <div class="input-group-addon">
                                                <span class="glyphicon glyphicon-th"></span>
                                            </div>
                                        </div>

                                    </div>
                                    @Html.ValidationMessageFor(m => m.NoticeDate)
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                @Html.LabelFor(model => model.NoticeStatus, htmlAttributes: new { @class = "control-label col-md-12 col-sm-12 col-xs-12", style = "margin-bottom:10px" })
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    @Html.DropDownListFor(model=>model.NoticeStatus, new SelectList(new List<SelectListItem>{
                                            
                                            new SelectListItem { Text="Publish", Value="true"},
                                            new SelectListItem { Text="Unpublish", Value="false"},

                                        },"Value","Text"), new { @class = " js-example-basic-single form-control ", name = "AspCMSSlider.SliderStatus" })
                                </div>
                            </div>
                            <div class="form-group clearfix">
                                <label class="control-label col-md-12 col-sm-12 col-xs-12" style="margin-bottom:10px"></label>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="file_uploader">
                                        <span id="filename">Select your file</span>
                                        <label for="file-upload"><input type="file" name="AttFile" id="AttFile" class="file_up"></label>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                    <div class="ln_solid"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-12 text-center col-sm-12 col-xs-12 ">
                                    <a href="/Notice/" class="btn btn-primary" type="button">Cancel</a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(function () {
            $('#NoticeDescription').summernote({
                height: 250,
                dialogsInBody: true,
                prettifyHtml: true,
                codemirror: {
                    "mode": "text/html",
                    "htmlMode": true,
                    "lineNumbers": true,
                    "theme": "monokai",
                    "width": "100px",
                    "textWrapping": true
                },
                disableDragAndDrop: true,
                toolbar: [
                    ["paragraph", ["style"]],
                    ["fontsize", ["fontname", "fontsize", "color"]],
                    ["style", ["bold", "italic", "underline", "strikethrough", "clear"]],
                    ["paragraph", ["ol", "ul", "paragraph"]],
                    ["insert", ["table", "link", "picture", "video", "hr"]],
                    ["misc", ["codeview"]]
                ],
                placeholder: "Page Content"
            });
        });

    </script>


}

MangroveSpace/Views/Notice/Index.cshtml
@model IEnumerable<dynamic>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}



<div class="row">
    <div class="col-md-12">
        <div class="page-title">
            <div class="row">
                <div class="col-md-6">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="col-md-6 text-right">
                    <a href="@Url.Action("Create", "Notice")" class="btn btn-success">Add Notice</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">

                <div class="table-responsive">
                    <table id="noticetable" class="noticetable table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Notice ID</th>
                                <th>NoticeOrderID</th>
                                <th>NoticeName</th>
                                <th>Status</th>
                                <th class="text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {

                                foreach (dynamic item in Model)
                                {
                                    <tr>
                                        <td>@item.NoticeID</td>
                                        <td>@item.NoticeID</td>
                                        <td>@item.NoticeOrderID</td>
                                        <td>@item.NoticeName</td>
                                        <td>
                                            @{

                                                if (item.NoticeStatus == true)
                                                {
                                                    <p>Active</p>
                                                }
                                                else
                                                {
                                                    <p>Inactive</p>
                                                }

                                            }
                                        </td>
                                        <td class="col-md-2" align="right">
                                            <div class="btn-toolbar">
                                                <div class="btn-group pull-right" style="margin:10px 0">

                                                    @{
                                                        if (item.NoticeStatus == true)
                                                        {
                                                            <a href='@Url.Action("StatusInactive", "Notice", new { id = item.ID })' class="btn btn-success btn-xs" data-original-title="Inactive"><i class="glyphicon glyphicon-arrow-up"></i></a>
                                                        }
                                                        else
                                                        {
                                                            <a href='@Url.Action("StatusActive", "Notice", new { id = item.ID })' class="btn btn-danger btn-xs" data-original-title="Active"><i class="glyphicon glyphicon-arrow-down"></i></a>


                                                        }


                                                    }
                                                    <a href='@Url.Action("Increment", "Notice", new { id = @item.ID })' class="btn btn-icon-toggle btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Increment"><i class="fa fa-arrow-up"></i></a>
                                                    <a href='@Url.Action("Decrement", "Notice", new { id = @item.ID })' class="btn btn-icon-toggle btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Decrement"><i class="fa fa-arrow-down"></i></a>
                                                    <a class="btn btn-icon-toggle btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Edit" href="@Url.Action("Edit", "Notice", new {id = @item.ID})"><i class="fa fa-pencil"></i></a>
                                                    <a class="btn btn-icon-toggle btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Edit" href="@Url.Action("CodeViewEdit", "Notice", new {id = @item.ID})"><i class="fa fa-code"></i></a>
                                                    <a href="Notice/Delete/@item.ID" class="btn btn-icon-toggle btn-danger btn-xs alert_warning" data-toggle="tooltip" data-placement="top" data-original-title="Delete" data-ntc-id=@item.ID><i class="fa fa-trash-o"></i></a>
                                                </div>
                                            </div>

                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>



            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        var table = $(".noticetable").DataTable({
            "aLengthMenu": [[100, 150, 175, -1], [100, 150, 175, "All"]],
            "iDisplayLength": 100,
            "ordering": false
        });
    </script>




}

MangroveSpace/Views/Notice/NoticeDetails.cshtml
@model IEnumerable<dynamic>

@{

    Layout = Layout = "~/Views/Shared/frontend/" + this.Session["ThemeName"] + "/_InnerPageLayout.cshtml";
    ViewBag.Title = "Notice";
}

@{
    Html.RenderPartial("~/Views/Shared/frontend/" + this.Session["ThemeName"] + "/_NoticeSinglePartialLayout.cshtml");
}