MangroveSpace/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangroveSpace;
using MapProject;
using Microsoft.AspNet.Identity;

namespace MapProject.Controllers
{
    public class LocationController : Controller
    {
        private MangroveSpaceEntities db = new MangroveSpaceEntities();

        // GET: Location
        public ActionResult Index()
        {
            var PowerPlant_Main = db.PowerPlant_Main.Include(l => l.PowerPlant_Category);
            return View(PowerPlant_Main.ToList());
        }

        public ActionResult UpdateDetailsPage(string pagetitle)
        {
            try
            {
                if (pagetitle == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                AspCMSPage aspCMSPage = db.AspCMSPages.Where(s => s.PageID == pagetitle).FirstOrDefault();
                if (aspCMSPage == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(aspCMSPage);
                }

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateDetailsPage(AspCMSPage AspCMSPage)
        {
            db.Entry(AspCMSPage).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateDetailsPageCode(string pagetitle)
        {
            try
            {
                if (pagetitle == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                AspCMSPage aspCMSPage = db.AspCMSPages.Where(s => s.PageID == pagetitle).FirstOrDefault();
                if (aspCMSPage == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(aspCMSPage);
                }

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PowerPlant_Main PowerPlant_Main = db.PowerPlant_Main.Find(id);
                AspCMSPage aspCMSPage = db.AspCMSPages.Where(s => s.PageID == PowerPlant_Main.DetailsPageAddress).FirstOrDefault();

                if (PowerPlant_Main == null)
                {
                    return HttpNotFound();
                }
                db.AspCMSPages.Remove(aspCMSPage);
                db.PowerPlant_Main.Remove(PowerPlant_Main);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangroveSpace/Controllers/PagesController.cs
using MangroveSpace.Models;
using System;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using MapProject.Service;

namespace MangroveSpace.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class PagesController : Controller
    {
        private MangroveSpaceEntities db = new MangroveSpaceEntities();
        MapDataPreparation mapService = new MapDataPreparation();

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }

        // GET: Pages
        [Authorize]
        public ActionResult Index()
        {
            try
            {

                string sql = "select A.[ID], PageID, PageTitle, PageTamplateID, PageLanguage, B.[CategoryName], C.[TemplateName] from [dbo].[AspCMSPage] A Left join [dbo].[AspCMSCategory] B on A.[CategoryID] = B.[CategoryID] Left join [dbo].[AspCMSPageTemplate] C on A.[PageTamplateID] = C.[TemplateID] where A.TAG IS NULL OR A.TAG NOT IN ('PP', 'M')";

                List<dynamic> Information = Global.Sql(db, sql).ToList();
                return View(Information);

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }


        [Authorize]
        public ActionResult Create()
        {
            try
            {
                var CategoryList = db.Database.SqlQuery<IntList>("select [CategoryID] as [ID], isnull( [CategoryName],'')+ ' > ' + isnull([CategoryContentType],'') as [value] from [dbo].[AspCMSCategory] order by [CategoryID]").ToList();
                ViewBag.CategoryList = CategoryList;

                var TemplateList = db.Database.SqlQuery<StringList>("select [TemplateID] as [ID], isnull([TemplateName],'') as [value]  from [dbo].[AspCMSPageTemplate]").ToList();
                ViewBag.TemplateList = TemplateList;

                return View();

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }


        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "ID,PageID,PageTitle,PageBody,PageTamplateID,PageType,PageLanguage,"+
            "Aproved,ApprovedBy,CategoryID,TAG")] AspCMSPage aspCMSPage)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int count = 0;
                    string PageID = Convert.ToString(aspCMSPage.PageTitle);
                    PageID = PageID.Replace(" ", "");

                Ck:
                    int ck_name = Global.exec("select count(*) from AspCMSPage where PageID ='" + PageID + "'", 0);
                    if (ck_name != 0)
                    {
                        count++;
                        PageID = PageID + Convert.ToString(count);
                        goto Ck;
                    }


                    aspCMSPage.PageID = PageID;
                    aspCMSPage.EntryBy = User.Identity.GetUserId();
                    aspCMSPage.EntryDate = DateTime.Now;
                    aspCMSPage.Aproved = true;
                    aspCMSPage.ApprovedBy = User.Identity.GetUserId();
                    db.AspCMSPages.Add(aspCMSPage);
                    db.SaveChanges();
                    TempData["msg"] = "Data Successfuly Saved";
                    return RedirectToAction("Index");

                }
                var CategoryList = db.Database.SqlQuery<IntList>("select [CategoryID] as [ID], isnull( [CategoryName],'')+ ' > ' + isnull([CategoryContentType],'') as [value] from [dbo].[AspCMSCategory] order by [CategoryID]").ToList();
                ViewBag.CategoryList = CategoryList;

                var TemplateList = db.Database.SqlQuery<StringList>("select [TemplateID] as [ID], isnull([TemplateName],'') as [value]  from [dbo].[AspCMSPageTemplate]").ToList();
                ViewBag.TemplateList = TemplateList;

                return View(aspCMSPage);

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }


        }

        [Authorize]
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Edit(int id)
        {
            try
            {
                var CategoryList = db.Database.SqlQuery<IntList>("select [CategoryID] as [ID], isnull( [CategoryName],'')+ ' > ' + isnull([CategoryContentType],'') as [value] from [dbo].[AspCMSCategory] order by [CategoryID]").ToList();
                ViewBag.CategoryList = CategoryList;

                var TemplateList = db.Database.SqlQuery<StringList>("select [TemplateID] as [ID], isnull([TemplateName],'') as [value]  from [dbo].[AspCMSPageTemplate]").ToList();
                ViewBag.TemplateList = TemplateList;

                //var HtmString  = db.Database.SqlQuery<String>("select [TemplateID] as [ID], isnull([TemplateName],'') as [value]  from [dbo].[AspCMSPageTemplate]").S;

                if (id == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                AspCMSPage aspCMSPage = db.AspCMSPages.Find(id);
                if (aspCMSPage == null)
                {
                    return HttpNotFound();
                }
                return View(aspCMSPage);

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }


        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "ID,PageTitle,PageBody,PageTamplateID,PageType,PageLanguage,CategoryID,TAG")] AspCMSPage aspCMSPage)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    aspCMSPage.ModifyDate = DateTime.Now;
                    aspCMSPage.ModifyBy = User.Identity.GetUserId();
                    db.Entry(aspCMSPage).State = EntityState.Modified;
                    db.Entry(aspCMSPage).Property(e => e.PageID).IsModified = false;
                    db.Entry(aspCMSPage).Property(e => e.EntryBy).IsModified = false;
                    db.Entry(aspCMSPage).Property(e => e.EntryDate).IsModified = false;
                    db.Entry(aspCMSPage).Property(e => e.Aproved).IsModified = false;
                    db.Entry(aspCMSPage).Property(e => e.ApprovedBy).IsModified = false;
                    db.SaveChanges();

                    TempData["msg"] = "Data Successfuly Updated";
                    return RedirectToAction("Index");
                }
                else
                {
                    var CategoryList = db.Database.SqlQuery<IntList>("select [CategoryID] as [ID], isnull( [CategoryName],'')+ ' > ' + isnull([CategoryContentType],'') as [value] from [dbo].[AspCMSCategory] order by [CategoryID]").ToList();

MangroveSpace/Views/Location/CreateWithLatLong.cshtml
@model MapProject.Location_Details

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Location Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Loc_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Loc_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loc_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loc_Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Loc_Latitude, new { htmlAttributes = new { Value = ViewBag.latitude, @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loc_Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loc_Logitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Loc_Logitude, new { htmlAttributes = new { Value = ViewBag.longitude, @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loc_Logitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details_Page, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details_Page, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details_Page, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MangroveSpace/Views/Location/Index.cshtml
@model IEnumerable<PowerPlant_Main>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="page-title">
            <div class="row">
                <div class="col-md-6">
                    <h3>@ViewBag.Title</h3>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <div class="table-responsive">
                    <table class="PP table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>
                                    Power Plant Name
                                </th>
                                <th>
                                    Country
                                </th>
                                <th>
                                    Latitude
                                </th>
                                <th>
                                    Longitude
                                </th>
                                <th>
                                    Address
                                </th>
                                <th></th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PowerPlant_Country.Country_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Latitude)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Longitude)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Location)
                                    </td>
                                    <td>
                                        <a class="btn btn-icon-toggle  btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Edit row" href="@Url.Action("UpdateDetailsPage", "Location", new { pagetitle = @item.DetailsPageAddress })"><i class="fa fa-pencil"></i></a>
                                        <a class="btn btn-icon-toggle  btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Code Edit" href="@Url.Action("UpdateDetailsPageCode", "Location", new { pagetitle = @item.DetailsPageAddress })"><i class="fa fa-code"></i></a>
                                        @*<a class="btn btn-icon-toggle  btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Edit row" href="@Url.Action("Edit", "Pages", new { id = @item.ID })"><i class="fa fa-pencil"></i></a>
        <a class="btn btn-icon-toggle  btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Code Edit" href="@Url.Action("pageCodeEdit", "Pages", new { id = @item.ID })"><i class="fa fa-code"></i></a>*@
                                        <a class="btn btn-icon-toggle btn-danger btn-xs alert_warning" data-toggle="tooltip" data-placement="top" data-original-title="Delete" data-pp-id=@item.ID><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
    </div>
</div>

MangroveSpace/Views/Location/UpdateDetailsPage.cshtml
@model AspCMSPage
@*PowerPlant_General*@
@{
    ViewBag.Title = "Add Page (Power Plant)";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="page-title">
            <div class="row">
                <div class="col-md-6">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="col-md-6 text-right">
                    <a href="/Location/" class="btn btn-success">Manage Page</a>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="row">


    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <br />
                @using (Html.BeginForm("UpdateDetailsPage", "Location", FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                {
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.PageID)
                    @Html.HiddenFor(model => model.PageTitle)
                    @Html.HiddenFor(model => model.PageTamplateID)
                    @Html.HiddenFor(model => model.PageType)
                    @Html.HiddenFor(model => model.PageLanguage)
                    @Html.HiddenFor(model => model.Aproved)
                    @Html.HiddenFor(model => model.ApprovedBy)
                    @Html.HiddenFor(model => model.CategoryID)
                    @Html.HiddenFor(model => model.TAG)
                    @Html.HiddenFor(model => model.EntryDate)
                    @Html.HiddenFor(model => model.EntryBy)
                    @Html.HiddenFor(model => model.AccessID)

                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="control-label col-md-12 col-sm-12 col-xs-12" style="margin-bottom:10px">Details Page</div>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    @*<div id="page-editor"></div>*@
                                    <div class="code-container">
                                        @Html.TextAreaFor(model => model.PageBody)
                                        @Html.ValidationMessageFor(m => m.PageBody)
                                    </div>
                                    <a class="btn btn-info pull-right btn-xs" style="margin-top:5px;margin-right:0" href="javascript:autoFormatSelection()">
                                        <i class="fa fa-check"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">

                        </div>
                    </div>


                    <div class="ln_solid"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-12 text-center col-sm-12 col-xs-12 ">
                                    <a href="/Location/" class="btn btn-primary" type="button">Cancel</a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(function () {
            $('#PageBody').summernote({
                height: 250,
                dialogsInBody: true,
                prettifyHtml: true,
                codemirror: {
                    "mode": "text/html",
                    "htmlMode": true,
                    "lineNumbers": true,
                    "theme": "monokai",
                    "width": "100px",
                    "textWrapping": true
                },
                disableDragAndDrop: true,
                toolbar: [
                    ["paragraph", ["style"]],
                    ["fontsize", ["fontname", "fontsize", "color"]],
                    ["style", ["bold", "italic", "underline", "strikethrough", "clear"]],
                    ["paragraph", ["ol", "ul", "paragraph"]],
                    ["insert", ["table", "link", "picture", "video", "hr"]],
                    ["misc", ["codeview"]]
                ],
                placeholder: "Page Content"
            });
        });

    </script>
}