MangroveSpace/Controllers/ProductInfoesController.cs
using System;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangroveSpace.ViewModel;
using MangroveSpace;

namespace MangroveSpace.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class ProductInfoesController : Controller
    {
        private MangroveSpaceEntities db = new MangroveSpaceEntities();


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }

        // GET: ProductInfoes
        public ActionResult Index()
        {
            try
            {

            var viewModel = new ProductInfoesViewModel
            {
                AspCMSProductInfoes = Global.Sql(db, "SELECT [ID], [ProductID],[CategoryID],[Product],[Brand],[CategoryName],[Status],[FeaturedStatus] FROM [dbo].[ProductInfoView]").ToList(),
            };

            return View(viewModel);
            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }




        // GET: ProductInfoes/Create
        public ActionResult Create()
        {
            try
            {
            var aspCMSProductInfo = new AspCMSProductInfo();
            aspCMSProductInfo.ProductID = db.Database.SqlQuery<string>("SELECT [dbo].[GenProductInfo](2)").Single();
            var viewModel = new ProductInfoesViewModel
            {
                AspCMSProductInfo = aspCMSProductInfo,
                AspCMSProductCategorys = Global.Sql(db, "SELECT [Id],[CategoryID],[CategoryName] FROM [AspCMSProductCategory]").ToList(),


            };
            return View(viewModel);

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }

        // POST: ProductInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,BarCode,Product,ProductSlag,Brand,BrandInfo,CategoryID,Color,Unit,WebSellRate,WebBuyRate,WebSellPreRate,Status,FeaturedStatus,InVal,SubSectorID,Vat,CreateDate,SNID,Warranty,UIDENTITY,img1,img2,img3,img4,img5,FeatureImgPath,Description1,Description2,Description3,EntryDate,EntryBy,ModifyDate,ModifyBy")] AspCMSProductInfo aspCMSProductInfo, HttpPostedFileBase ImageFile, HttpPostedFileBase ImageFile2, HttpPostedFileBase ImageFile3, HttpPostedFileBase ImageFile4, HttpPostedFileBase ImageFile5, HttpPostedFileBase ImageFile6)
        {
            try
            {
            if (ModelState.IsValid)
            {
                if (ImageFile != null)
                {
                    var AttachFileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                    var attachFileExt = Path.GetExtension(ImageFile.FileName);
                    AttachFileName = aspCMSProductInfo.ProductID + attachFileExt;
                    var AttachFolderPath = "/Uploads/CategoryIcon/" + AttachFileName;

                    AttachFileName = Path.Combine(Server.MapPath("~/Uploads/CategoryIcon/"), AttachFileName);
                    ImageFile.SaveAs(AttachFileName);
                    aspCMSProductInfo.img1 = AttachFolderPath;
                }

                if (ImageFile2 != null)
                {
                    var AttachFileName = Path.GetFileNameWithoutExtension(ImageFile2.FileName);
                    var attachFileExt = Path.GetExtension(ImageFile2.FileName);
                    AttachFileName = aspCMSProductInfo.ProductID + attachFileExt;
                    var AttachFolderPath = "/Uploads/CategoryIcon/" + AttachFileName;

                    AttachFileName = Path.Combine(Server.MapPath("~/Uploads/CategoryIcon/"), AttachFileName);
                    ImageFile2.SaveAs(AttachFileName);
                    aspCMSProductInfo.img2 = AttachFolderPath;
                }

                if (ImageFile3 != null)
                {
                    var AttachFileName = Path.GetFileNameWithoutExtension(ImageFile3.FileName);
                    var attachFileExt = Path.GetExtension(ImageFile3.FileName);
                    AttachFileName = aspCMSProductInfo.ProductID + attachFileExt;
                    var AttachFolderPath = "/Uploads/CategoryIcon/" + AttachFileName;

                    AttachFileName = Path.Combine(Server.MapPath("~/Uploads/CategoryIcon/"), AttachFileName);
                    ImageFile3.SaveAs(AttachFileName);
                    aspCMSProductInfo.img3 = AttachFolderPath;
                }
                if (ImageFile4 != null)
                {
                    var AttachFileName = Path.GetFileNameWithoutExtension(ImageFile4.FileName);
                    var attachFileExt = Path.GetExtension(ImageFile4.FileName);
                    AttachFileName = aspCMSProductInfo.ProductID + attachFileExt;
                    var AttachFolderPath = "/Uploads/CategoryIcon/" + AttachFileName;

                    AttachFileName = Path.Combine(Server.MapPath("~/Uploads/CategoryIcon/"), AttachFileName);
                    ImageFile4.SaveAs(AttachFileName);
                    aspCMSProductInfo.img4 = AttachFolderPath;
                }

                if (ImageFile5 != null)
                {
                    var AttachFileName = Path.GetFileNameWithoutExtension(ImageFile5.FileName);
                    var attachFileExt = Path.GetExtension(ImageFile5.FileName);
                    AttachFileName = aspCMSProductInfo.ProductID + attachFileExt;
                    var AttachFolderPath = "/Uploads/CategoryIcon/" + AttachFileName;

                    AttachFileName = Path.Combine(Server.MapPath("~/Uploads/CategoryIcon/"), AttachFileName);
                    ImageFile5.SaveAs(AttachFileName);
                    aspCMSProductInfo.img5 = AttachFolderPath;
                }

                if (ImageFile6 != null)
                {
                    var AttachFileName = Path.GetFileNameWithoutExtension(ImageFile6.FileName);
                    var attachFileExt = Path.GetExtension(ImageFile6.FileName);
                    AttachFileName = aspCMSProductInfo.ProductID + attachFileExt;
                    var AttachFolderPath = "/Uploads/CategoryIcon/" + AttachFileName;

                    AttachFileName = Path.Combine(Server.MapPath("~/Uploads/CategoryIcon/"), AttachFileName);
                    ImageFile6.SaveAs(AttachFileName);
                    aspCMSProductInfo.FeatureImgPath = AttachFolderPath;
                }

                aspCMSProductInfo.EntryDate = DateTime.Now;
                aspCMSProductInfo.ModifyDate = DateTime.Now;
                aspCMSProductInfo.EntryBy = User.Identity.GetUserName();
                aspCMSProductInfo.ModifyBy = User.Identity.GetUserName();
                db.AspCMSProductInfoes.Add(aspCMSProductInfo);
                db.SaveChanges();
                TempData["msg"] = "Successfuly Saved";
                return RedirectToAction("Index");
            }

            var aspCMSProductInfoes = new AspCMSProductInfo();
            var viewModel = new ProductInfoesViewModel
            {
                AspCMSProductInfo = aspCMSProductInfo,
                AspCMSProductCategorys = Global.Sql(db, "SELECT [Id],[CategoryID],[CategoryName] FROM [AspCMSProductCategory]").ToList(),

            };
            return View(viewModel);

            }
            catch (Exception ex)
            {
                string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
                string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                db.Database.ExecuteSqlCommand("INSERT INTO [dbo].[AspSysError](UserName,EntryBy,ModifyBy,ActionName,ControllerName,ErrorTime,EntryDate,ModifyDate,ErrorMessage)VALUES('" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + User.Identity.GetUserName().ToString() + "','" + actionName + "','" + controllerName + "', '" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "','" + DateTime.Now.ToString() + "', '" + ex.ToString().Replace("'", "") + "')");
                return Redirect(Request.UrlReferrer.ToString());
            }

        }

MangroveSpace/Views/ProductInfoes/Delete.cshtml
@model MangroveSpace.AspCMSProductInfo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspCMSProductInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BarCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BarCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductSlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductSlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrandInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebSellRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebSellRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebBuyRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebBuyRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebSellPreRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebSellPreRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeaturedStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeaturedStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubSectorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubSectorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SNID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SNID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UIDENTITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UIDENTITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeatureImgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeatureImgPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntryBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifyBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MangroveSpace/Views/ProductInfoes/Details.cshtml
@model MangroveSpace.AspCMSProductInfo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AspCMSProductInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BarCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BarCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductSlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductSlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrandInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebSellRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebSellRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebBuyRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebBuyRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebSellPreRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebSellPreRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeaturedStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeaturedStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubSectorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubSectorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SNID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SNID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UIDENTITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UIDENTITY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeatureImgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeatureImgPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntryBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifyBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyBy)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MangroveSpace/Views/ProductInfoes/Index.cshtml
@model MangroveSpace.ViewModel.ProductInfoesViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/backend/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="page-title">
            <div class="row">
                <div class="col-md-6">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="col-md-6 text-right">
                    <a href="@Url.Action("Create", "ProductInfoes")" class="btn btn-success">Add ProductInfoes</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <div class="table-responsive">
                    <table id="Producttable" class=" table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Product ID</th>
                                <th>Product Name</th>
                                <th>Brand</th>
                                <th>Category Name</th>
                                <th>Status</th>
                                <th>Featured Status</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (dynamic item in Model.AspCMSProductInfoes)
                                {
                                    <tr>
                                        <td>@item.ProductID</td>
                                        <td>@item.Product</td>
                                        <td>@item.Brand</td>
                                        <td>@item.CategoryName</td>

                                        <td>
                                            @{
                                                if (item.Status == true)
                                                {
                                                    <p>Active</p>
                                                }
                                                else
                                                {
                                                    <p>Inactive</p>
                                                }
                                            }
                                        </td>
                                        <td>
                                            @{ 
                                                if(item.FeaturedStatus == true)
                                                {
                                                    <p>Yes</p>
                                                }
                                                else
                                                {
                                                    <p>No</p>
                                                }
                                            }
                                        </td>
                                        <td class="col-md-2" align="right">
                                            <div class="btn-toolbar">
                                                <div class="btn-group pull-right" style="margin:10px 0">
                                                    @{
                                                        if (item.Status == true)
                                                        {
                                                            <a href='@Url.Action("StatusInactive", "ProductCategory", new { id = item.ID })' class="btn btn-danger btn-xs" data-original-title="Inactive"><i class="glyphicon glyphicon-arrow-down"></i></a>
                                                        }
                                                        else
                                                        {
                                                            <a href='@Url.Action("StatusActive", "ProductCategory", new { id = item.ID })' class="btn btn-primary btn-xs" data-original-title="Active"><i class="glyphicon glyphicon-arrow-up"></i></a>
                                                        }
                                                    }
                                                    <a class="btn btn-icon-toggle btn-primary btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="Edit" href="@Url.Action("Edit", "ProductInfoes", new {id = @item.ID})"><i class="fa fa-pencil"></i></a>
                                                    <a href="/ProductInfoes/Delete/@item.ID" class="btn btn-icon-toggle btn-danger btn-xs alert_warning" data-toggle="tooltip" data-placement="top" data-original-title="Delete" data-Product-id=@item.ID><i class="fa fa-trash-o"></i></a>

                                                </div>

                                            </div>

                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>

                    </table>

                </div>

            </div>

        </div>

    </div>

</div>

@section Scripts{
    <script>
        var table = $("#Producttable").DataTable({
            "aLengthMenu": [[100, 150, 175, -1], [100, 150, 175, "All"]],
            "iDisplayLength": 100
        });
    </script>




}